### PR TITLE
Change single-chapter reference output to include chapter number.

### PR DESCRIPTION
**Pull request by derikolsson**
Philemon 1:12, not Philemon 12, for example.

### CODE REVIEW

**Comment by jeffmcfadden** [comment]
Thoughts on preserving the old behavior as an option for contexts where it might be desired?

**Comment by derikolsson** [comment]
I wondered that too... are you thinking putting this under a new reference method?

**Comment by jeffmcfadden** [comment]
I was thinking maybe allow an optional Param with formatting options, allow one called force chapter numbers in all cases or something like that. Defaults to old behavior

**Comment by derikolsson** [comment]
Hah. I originally did but rolled back for broader support. Forgot that the limitation is not Ruby (that's 2.0+), but rather Sidekiq (which still doesn't support them to this day).

**Pull request merged**
